package com.safeshade.platform

import com.safeshade.data.EmergencyContact
import com.safeshade.data.MedicalId
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class IncidentPdfTest {

    private fun report(
        wearerName: String = "Baba",
        kind: String = "Fall detected",
        at: Long = 1_700_000_000_000L,
        outcome: String = "Emergency contacted",
        contacted: Boolean = true,
        lat: Double? = 22.5726,
        lon: Double? = 88.3639,
        medicalId: MedicalId? = MedicalId(bloodType = "O+", allergies = "Penicillin"),
        contacts: List<EmergencyContact> = emptyList(),
        timeline: List<Pair<Long, String>> = emptyList(),
        evidenceNote: String? = null,
    ) = IncidentReport(
        id = "abc123",
        wearerName = wearerName,
        kind = kind,
        at = at,
        outcome = outcome,
        contacted = contacted,
        lat = lat,
        lon = lon,
        medicalId = medicalId,
        contacts = contacts,
        timeline = timeline,
        evidenceNote = evidenceNote,
    )

    @Test
    fun `null and blank facts render as a dash, never as blank or hedged text`() {
        val lines = IncidentPdf.layoutLines(
            report(wearerName = "", lat = null, lon = null, medicalId = null),
            width = 500f,
        )

        assertTrue(lines.any { it == "Wearer: —" })
        assertTrue(lines.any { it == "Location: —" })
        assertTrue(lines.any { it.startsWith("No medical ID on file") })
        for (line in lines) {
            assertTrue("line leaked hedging copy: $line", !line.contains("planned", ignoreCase = true))
            assertTrue("line leaked hedging copy: $line", !line.contains("simulated", ignoreCase = true))
        }
    }

    @Test
    fun `known facts are never replaced with a dash`() {
        val lines = IncidentPdf.layoutLines(report(), width = 500f)

        assertTrue(lines.any { it == "Wearer: Baba" })
        assertTrue(lines.any { it == "Type: Fall detected" })
        assertTrue(lines.any { it.startsWith("Location: 22.5") })
        assertTrue(lines.any { it == "Blood type: O+" })
    }

    @Test
    fun `a long list wraps across multiple lines instead of overflowing one`() {
        val longAllergyList = (1..30).joinToString(", ") { "allergen-$it" }
        val medicalId = MedicalId(bloodType = "A+", allergies = longAllergyList)

        val lines = IncidentPdf.layoutLines(report(medicalId = medicalId), width = 300f)

        val allergyLines = lines.filter { it.contains("allergen-") }
        assertTrue("expected the long allergy list to wrap onto more than one line", allergyLines.size > 1)
        for (line in allergyLines) {
            assertTrue("wrapped line too long: '$line' (${line.length} chars)", line.length <= 60)
        }
    }

    @Test
    fun `contacts render name, phone, relationship and dash for missing fields`() {
        val contacts = listOf(
            EmergencyContact(name = "Maa", phone = "9830011223", isPrimary = true, relationship = "Mother"),
            EmergencyContact(name = "", phone = "", isPrimary = false, relationship = ""),
        )
        val lines = IncidentPdf.layoutLines(report(contacts = contacts), width = 500f)

        assertTrue(lines.any { it.contains("Maa") && it.contains("9830011223") && it.contains("Mother") && it.contains("[primary]") })
        assertTrue(lines.any { it == "— — —" })
    }

    @Test
    fun `timeline entries and footer are present`() {
        val timeline = listOf(1_700_000_000_000L to "Fall detected", 1_700_000_060_000L to "Contact dialled")
        val lines = IncidentPdf.layoutLines(report(timeline = timeline), width = 500f)

        assertTrue(lines.any { it.contains("Fall detected") && it.contains("—") })
        assertTrue(lines.any { it.startsWith("Generated by SafeShade on") })
    }

    @Test
    fun `pagesFor rounds up and never returns fewer than one page`() {
        assertEquals(1, IncidentPdf.pagesFor(lineCount = 0, linesPerPage = 40))
        assertEquals(1, IncidentPdf.pagesFor(lineCount = 40, linesPerPage = 40))
        assertEquals(2, IncidentPdf.pagesFor(lineCount = 41, linesPerPage = 40))
        assertEquals(3, IncidentPdf.pagesFor(lineCount = 81, linesPerPage = 40))
        assertEquals(1, IncidentPdf.pagesFor(lineCount = 5, linesPerPage = 0))
    }
}
